package OrmMapping;
// Generated Mar 17, 2017 5:20:45 PM by Hibernate Tools 4.3.1



/**
 * CandidatesEntretien generated by hbm2java
 */
public class CandidatesEntretien  implements java.io.Serializable {


     private Integer id;
     private Candidates candidates;
     private Jobs jobs;
     private int phase;

    public CandidatesEntretien() {
    }

    public CandidatesEntretien(Candidates candidates, Jobs jobs, int phase) {
       this.candidates = candidates;
       this.jobs = jobs;
       this.phase = phase;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Candidates getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Candidates candidates) {
        this.candidates = candidates;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public int getPhase() {
        return this.phase;
    }
    
    public void setPhase(int phase) {
        this.phase = phase;
    }




}


