package OrmMapping;
// Generated Mar 16, 2017 7:03:51 PM by Hibernate Tools 4.3.1



/**
 * CandidatesEntretien generated by hbm2java
 */
public class CandidatesEntretien  implements java.io.Serializable {


     private int candidatesid;
     private Candidates candidates;
     private Jobs jobs;
     private int phase;

    public CandidatesEntretien() {
    }

    public CandidatesEntretien(Candidates candidates, Jobs jobs, int phase) {
       this.candidates = candidates;
       this.jobs = jobs;
       this.phase = phase;
    }
   
    public int getCandidatesid() {
        return this.candidatesid;
    }
    
    public void setCandidatesid(int candidatesid) {
        this.candidatesid = candidatesid;
    }
    public Candidates getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Candidates candidates) {
        this.candidates = candidates;
    }
    public Jobs getJobs() {
        return this.jobs;
    }
    
    public void setJobs(Jobs jobs) {
        this.jobs = jobs;
    }
    public int getPhase() {
        return this.phase;
    }
    
    public void setPhase(int phase) {
        this.phase = phase;
    }




}


