package OrmMapping;
// Generated Mar 12, 2017 1:35:18 PM by Hibernate Tools 4.3.1



/**
 * CandidatesJobsId generated by hbm2java
 */
public class CandidatesJobsId  implements java.io.Serializable {


     private int candidatesid;
     private int jobsid;

    public CandidatesJobsId() {
    }

    public CandidatesJobsId(int candidatesid, int jobsid) {
       this.candidatesid = candidatesid;
       this.jobsid = jobsid;
    }
   
    public int getCandidatesid() {
        return this.candidatesid;
    }
    
    public void setCandidatesid(int candidatesid) {
        this.candidatesid = candidatesid;
    }
    public int getJobsid() {
        return this.jobsid;
    }
    
    public void setJobsid(int jobsid) {
        this.jobsid = jobsid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CandidatesJobsId) ) return false;
		 CandidatesJobsId castOther = ( CandidatesJobsId ) other; 
         
		 return (this.getCandidatesid()==castOther.getCandidatesid())
 && (this.getJobsid()==castOther.getJobsid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCandidatesid();
         result = 37 * result + this.getJobsid();
         return result;
   }   


}


