package OrmMapping;
// Generated Mar 16, 2017 4:24:54 PM by Hibernate Tools 4.3.1



/**
 * CandidatesEntretien generated by hbm2java
 */
public class CandidatesEntretien  implements java.io.Serializable {


     private int candidatesid;
     private Candidates candidates;
     private String phase;

    public CandidatesEntretien() {
    }

    public CandidatesEntretien(Candidates candidates, String phase) {
       this.candidates = candidates;
       this.phase = phase;
    }
   
    public int getCandidatesid() {
        return this.candidatesid;
    }
    
    public void setCandidatesid(int candidatesid) {
        this.candidatesid = candidatesid;
    }
    public Candidates getCandidates() {
        return this.candidates;
    }
    
    public void setCandidates(Candidates candidates) {
        this.candidates = candidates;
    }
    public String getPhase() {
        return this.phase;
    }
    
    public void setPhase(String phase) {
        this.phase = phase;
    }




}


