package OrmMapping;
// Generated Mar 16, 2017 7:03:51 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private Integer id;
     private Clients clients;
     private String profil;
     private int status;
     private Set jobDescriptions = new HashSet(0);
     private Set candidatesEntretiens = new HashSet(0);
     private Set candidatesJobses = new HashSet(0);

    public Jobs() {
    }

	
    public Jobs(Clients clients, String profil, int status) {
        this.clients = clients;
        this.profil = profil;
        this.status = status;
    }
    public Jobs(Clients clients, String profil, int status, Set jobDescriptions, Set candidatesEntretiens, Set candidatesJobses) {
       this.clients = clients;
       this.profil = profil;
       this.status = status;
       this.jobDescriptions = jobDescriptions;
       this.candidatesEntretiens = candidatesEntretiens;
       this.candidatesJobses = candidatesJobses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public String getProfil() {
        return this.profil;
    }
    
    public void setProfil(String profil) {
        this.profil = profil;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getJobDescriptions() {
        return this.jobDescriptions;
    }
    
    public void setJobDescriptions(Set jobDescriptions) {
        this.jobDescriptions = jobDescriptions;
    }
    public Set getCandidatesEntretiens() {
        return this.candidatesEntretiens;
    }
    
    public void setCandidatesEntretiens(Set candidatesEntretiens) {
        this.candidatesEntretiens = candidatesEntretiens;
    }
    public Set getCandidatesJobses() {
        return this.candidatesJobses;
    }
    
    public void setCandidatesJobses(Set candidatesJobses) {
        this.candidatesJobses = candidatesJobses;
    }

    @Override
    public String toString() {
        return this.profil ;
    }

    


}


