package OrmMapping;
// Generated Mar 12, 2017 1:35:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private Integer id;
     private Clients clients;
     private String profil;
     private int status;
     private Set jobDescriptions = new HashSet(0);
     private Set candidatesJobses = new HashSet(0);
     private Set entretiens = new HashSet(0);

    public Jobs() {
    }

    public Jobs(int id) {
        this.id = id ;
    } 
	
    public Jobs(Clients clients, String profil, int status) {
        this.clients = clients;
        this.profil = profil;
        this.status = status;
    }
    public Jobs(Clients clients, String profil, int status, Set jobDescriptions, Set candidatesJobses, Set entretiens) {
       this.clients = clients;
       this.profil = profil;
       this.status = status;
       this.jobDescriptions = jobDescriptions;
       this.candidatesJobses = candidatesJobses;
       this.entretiens = entretiens;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public String getProfil() {
        return this.profil;
    }
    
    public void setProfil(String profil) {
        this.profil = profil;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set getJobDescriptions() {
        return this.jobDescriptions;
    }
    
    public void setJobDescriptions(Set jobDescriptions) {
        this.jobDescriptions = jobDescriptions;
    }
    public Set getCandidatesJobses() {
        return this.candidatesJobses;
    }
    
    public void setCandidatesJobses(Set candidatesJobses) {
        this.candidatesJobses = candidatesJobses;
    }
    public Set getEntretiens() {
        return this.entretiens;
    }
    
    public void setEntretiens(Set entretiens) {
        this.entretiens = entretiens;
    }
    
     @Override
    public String toString(){
        return profil+"-"+this.getClients().getName();
    }



}


